inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "bin/*"

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true
  AutoCorrect: true

Metrics/MethodLength:
  Max: 15
  AutoCorrect: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  AutoCorrect: true
