inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "bin/*"

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true
  AutoCorrect: true
  Exclude:
    - "config/routes.rb"
    - "config/initializers/cors.rb"
    - "config/initializers/rswag.rb"
    - "config/initializers/rswag_ui.rb"

Metrics/MethodLength:
  Max: 15
  AutoCorrect: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  AutoCorrect: true
